[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**", "prisma/**"]

[build.environment]
  NODE_VERSION = "18"

# Netlify-specific configuration for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js for proper routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle API routes properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
