[build]
  command = "node scripts/setup-supabase && npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**", "prisma/**"]

[build.environment]
  NODE_VERSION = "18"

# Netlify-specific configuration for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# The @netlify/plugin-nextjs plugin handles routing automatically
# Remove manual redirects as they can interfere with the plugin
